project:
  type: website

website:
  title: "Olga Perski"
  google-analytics: "G-WF7G4G33CE"
  twitter-card: true
  open-graph: false
  page-navigation: true
  navbar:
    foreground: light
    background: dark
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        menu: 
          - text: "COMPLAPSE"
            href: research/complapse.qmd
            icon: phone
          - text: "EMASENS"
            href: research/emasens.qmd
          - text: "ODH Living Review & Database"
            href: research/odh.qmd
          - text: "Virtual Reality"
            href: research/vr.qmd
            icon: badge-vr
          - text: "Mental Wellbeing"
            href: research/swed.qmd
          - text: "Food Standards Agency, UK"
            href: research/fsa.qmd
          - text: "EMA Review"
            href: research/ema.qmd
          - text: "COVID-19"
            href: research/covid.qmd
          - text: "Engagement"
            href: research/engagement.qmd
          - text: "Smoking Toolkit Study"
            href: research/smoking.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "In The Media"
        href: media.qmd
      - text: "Teaching and Supervision"
        href: teaching.qmd
      - text: "Consultancies"
        href: consultancy.qmd
      - text: "Policy Engagement"
        href: policy.qmd
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    css: styles.css
    toc: true



