project:
  type: website

website:
  title: "Olga Perski"
  navbar:
    foreground: light
    background: dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



