---
title: "Policy engagement"
---

I have produced an evidence review written for the Royal College of Physicians (RCP), which was subsequently used to inform Public Health England’s (PHE) statement on smoking and COVID-19. Public Health England subsequently requested that the RCP review be converted into a living review. The review has since been updated 12 times, with the manuscript shared with PHE’s ‘tobacco and smoking cell’ directly and updated on a preprint server (with v7 published in a peer-reviewed journal). PHE referred to the review in response to a parliamentary question on smoking and COVID-19.

I was invited, alongside members of the UK SPI-B, to provide expert input into the development of the UK coronavirus contact tracing app.

I have contributed to health and technology policy formation by leading the UCL Centre for Behaviour Change’s submission to NICE’s consultation in preparation for updating their <a href="https://www.nice.org.uk/guidance/ng183">guideline on behaviour change to incorporate evidence on digital behaviour change interventions</a>. In 2019, I provided academic stakeholder input into NICE’s <a href="https://www.nice.org.uk/about/what-we-do/our-programmes/evidence-standards-framework-for-digital-health-technologies">Evidence Standards Framework for Digital Health Technologies</a>. In 2020, I was invited to provide input into the WHO–ITU mHealth Hub in EU’s <a href="https://mhealth-hub.org/download/d2-1-knowledge-tool-1-health-apps-assessment-frameworks">‘Knowledge Tool 1: Assessment Frameworks in mHealth’</a>.


