---
title: "Producing a Quality Assurance Toolkit for the UK Food Standards Agency"
---

During the production and assessment of high-quality research, it is important to be open about how that research was produced and what can be concluded from it. The <a href="https://www.food.gov.uk/">Food Standards Agency</a> (FSA) set out to develop a ‘good science’ Quality Assurance Toolkit (QAT) to support its members to produce, assess and procure high-quality research. 

I co-led the development of the FSA QAT in collaboration with Dr. Danielle D’Lima and Prof. Jamie Brown between February and August 2022 through a process of co-creation. We worked with the FSA and their Assurance Working Group to collaboratively develop the topics to be covered within the QAT. A series of focus groups were held with FSA staff in March 2022. This was followed by a scoping review of internal and external guidance to help populate the QAT. The QAT was iteratively developed through multiple rounds of feedback from the Advisory Committee for Social Science and piloting on several study protocols, research reports, and tender specifications between April and July 2022.

The QAT will be publicised on the FSA website in early 2023.
