---
title: "Mental Wellbeing in Swedish University Students During COVID-19"
---
As emerging adults, university students typically experience substantial changes to their living conditions, relationships and increased academic stress. In addition to any ‘normal’ changes to university students’ living situations in Sweden and beyond, the COVID-19 pandemic has profoundly impacted people's lives through, for example, prolonged periods of behavioural restrictions limiting physical interactions with family, peers and teachers.

Funded by the Swedish Public Health Authority (<a href="https://www.folkhalsomyndigheten.se/">"Folkhälsomyndigheten"</a>) and led by Prof. Anne Berman (Uppsala University) and Dr. Claes Andersson (Malmö University), this longitudinal survey study forms part of the larger <a href="https://pubmed.ncbi.nlm.nih.gov/30614123/">World Health Organisation World Mental Health International College Student Initiative (WHO-WMH-ICS)</a>.

As a project collaborator, I'm currently leading two studies examining i) the trajectory of mental wellbeing in Swedish university students during the COVID-19 pandemic and ii) Swedish university students' interest in and uptake of psychological treatment.

